// <auto-generated />
namespace PiniT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Authorize_Restaurant : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Authorize_Restaurant));
        
        string IMigrationMetadata.Id
        {
            get { return "201907261604085_Authorize_Restaurant"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
