// <auto-generated />
namespace PiniT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Account_Wallet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Account_Wallet));
        
        string IMigrationMetadata.Id
        {
            get { return "201907291308511_Account_Wallet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
